name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  SwiftLang:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-26, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v6

    - name: Package Resolution
      shell: bash
      run: swift package resolve

    - name: Build
      shell: bash
      run: swift build

    - name: Test
      shell: bash
      run: swift test
